Fix editor height for Firefox
bbc/codext pull request #11
Opened 2021-11-16 20:55 UTC by Roysten

From Firefox 94 the editor no longer fills the page. I resolved this by setting the height of all elements to 100% all the way from the html node to the iframe node. To make sure the iframe does not get a scrollbar we need to set its display style to block.

2021-11-17 22:06 UTC, PyvesB commented
Thanks for the contribution, will take a look this weekend!

2021-11-19 18:52 UTC, PyvesB requested changes
This change seems to have the intended effects on both Chrome and Firefox, thanks! 👍🏻 

In addition to the whitespace removal mentioned below, you'll need to update the following unit test which is now failing:
https://github.com/bbc/codext/blob/abaf359a5f76cf755ede9706d67eeaafffdc5dd2/tests/spec/ContentSpec.js#L72-L83

2021-11-19 18:52 UTC, PyvesB commented on src/content/content.js
> +function insertEditorFrame() {
The trailing whitespace change is unnecessary (and will create a diff when running `gulp prettify`). Could you please revert this line?

2021-11-21 11:23 UTC, Roysten commented
Hi, I think I resolved your comments. I'm not sure if the unit test works now, since I don't have the required libraries and do not want to install NPM because I do not trust it (given its issues in the past).

2021-11-21 12:58 UTC, PyvesB approved these changes
Test passes, thanks! Will liaise with some former colleagues to get this merged. :)

2021-12-04 19:46 UTC, danielthepope approved these changes
Hey @Roysten, thanks very much for your contribution! You've fixed the bug in both Firefox and Chrome 💯

2021-12-04 19:50 UTC, merged